### ISSUE TITLE
Receiving protocol error sometimes when using the HomeKey

### ISSUE THREAD

**Issue by peterrakolcza** [kormax/apple-home-key-reader#29]
Hey guys,

Most of the times everything works fine, however approximately every 1 of 5 attempts throw the following error. I am using _standard_ option in my `configuration.json` for flow.
```
[2024-05-04 02:11:04,043] [   ERROR] threads           :20   Unhandled exception in runner homekey. Continuing in 5 seconds
Traceback (most recent call last):
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 667, in send_cmd_recv_rsp
    return self.chipset.in_communicate_thru(data, timeout+0.1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 421, in in_communicate_thru
    self.chipset_error(data)
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 124, in chipset_error
    raise Chipset.Error(errno, strerr)
nfc.clf.pn53x.Chipset.Error: Error 0x0B: Protocol error during RF communication

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakolcza/apple-home-key-reader/util/threads.py", line 18, in function_
    target(*args, **kwargs)
  File "/home/rakolcza/apple-home-key-reader/service.py", line 185, in run
    self._read_homekey()
  File "/home/rakolcza/apple-home-key-reader/service.py", line 138, in _read_homekey
    result_flow, new_issuers_state, endpoint = read_homekey(
                                               ^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/homekey.py", line 737, in read_homekey
    result_flow, issuer, endpoint = perform_authentication_flow(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/homekey.py", line 598, in perform_authentication_flow
    k_persistent, endpoint, secure = standard_auth(
                                     ^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/homekey.py", line 305, in standard_auth
    response = tag.transceive(command)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/util/iso7816.py", line 199, in transceive
    self._implementation.transceive(
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/tag/tt4.py", line 437, in transceive
    data = self._dep.exchange(data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/tag/tt4.py", line 123, in exchange
    data = self.clf.exchange(data, (data[1] & 0x3F) * self.fwt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/__init__.py", line 1055, in exchange
    rcvd_data = exchange(self.target, send_data, timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakolcza/apple-home-key-reader/venv/lib/python3.11/site-packages/nfc/clf/pn53x.py", line 673, in send_cmd_recv_rsp
    raise nfc.clf.TransmissionError(str(error))
nfc.clf.TransmissionError: Error 0x0B: Protocol error during RF communication
```

**Comment by kormax** [comment]
This is an error caused by poor RF performance of the NFC module.

Nothing you can do about it apart from trying out another samples.

**Comment by peterrakolcza** [comment]
I am using an NFC MODUL V3 by Etechouse. Are there any better alternatives? Do you receive this errors too sometimes?

**Comment by kormax** [comment]
Weird that you're seeing them so much with an original module, consider that with mu fake ones it's rarer.

But yes, I usually encounter them from time to time.

**Comment by kormax** [comment]
What you can do to reduce the pain from this issue, is to reduce the restart timeout after a failure.

I think it's 3-5 seconds by default, you can set that value lower inside of the code.

**Comment by peterrakolcza** [comment]
Okay, thanks, will try that. Does the flow setting in the configuration.json make any difference? I am using the standard, but it is fast by default.

**Comment by kormax** [comment]
Flow setting affects the issue indirectly.

FAST flow uses less commands, meaning that there's less data sent back and forth, meaning that there's less chance for a communication error to occur.

**Comment by peterrakolcza** [comment]
I see, thanks for the clarification. But does that mean it is more insecure than standard or attestation?

**Comment by kormax** [comment]
I lack the sufficient formal knowledge about the cryptography to assess security of each flow.

But consider the facts:
- FAST flow is required to be supported by all official locks, and it's the default flow in all situations.
- Keys needed for fast flow are established via the STANDARD flow anyway.

**Comment by kormax** [comment]
BTW

The line you need to change in order to reduce timeout after a communication error, [is this one](https://github.com/kormax/apple-home-key-reader/blob/5c39b9cc3d5d71e2a0947bbd751c6efd38077fa9/service.py#L82).

**Comment by peterrakolcza** [comment]
I understand, thanks so much. **1 more thing: I have found that placing my phone very close to the NFC chip (almost touching), makes the protocol and authentication much more reliable.**

**Comment by kormax** [comment]
It depends on a per-unit bases.

Some work good from afar and bad from close, some work good at full range, etc.

[Here are my observations on the NFC chips and how they fare](https://github.com/kormax/apple-enhanced-contactless-polling/blob/main/examples/README.md)
